### ISSUE TITLE
Alpha candidates 74+ break SSR compatibility?

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [algolia/api-clients-automation#1884]
Not sure where to mention this, I couldn't figure out how or why.

But I was running algoliasearch in a Remix.run project using the `alpha` tag & yarn, which locked down to `v5.0.0-alpha.73` untill I refreshed the lockfile today, it bumped to `v5.0.0-alpha.77` and all the SSR compatibility went out the window.

Not sure what happened, but I stepped down to 76, then 74, and couldn't get it back working until 73.

So just an FYI I guess?

**Comment by shortcuts** [comment]
Hey @TheRealFlyingCoder, thanks for reporting the issue and testing the alpha package :)

The changelog is available [here](https://github.com/algolia/api-clients-automation/blob/main/clients/algoliasearch-client-javascript/CHANGELOG.md).

I was thinking the issue would be related to the ESM module migration introduced in .75 but since you mentioned only .73 works, I guess not.

in .74 we had a bunch of spec changes, which impacted every clients, which could've lead to breaking changes and build issues. Do you have more information on the error you encounter? Also, a minimal reproduction/snippet of the Algolia code you use would help

**Comment by TheRealFlyingCoder** [comment]
Oh it most certainly will be the esm module integration as that was the issue!

I must have got 74 and 75 mixed up.

I won't be able to add anything till tomorrow (6pm here) if you still need it

**Comment by shortcuts** [comment]
hey, https://github.com/algolia/api-clients-automation/pull/1894 seems to have fixed the issue, at least I can't reproduce anymore locally! Feel free to try and let me know :D
